// This file will be auto-generated by Supabase CLI
// Run: npx supabase gen types typescript --project-id <project-id> > src/types/database.ts
//
// For now, we define placeholder types based on the MVP spec

export type EntityType = "organization" | "venue";
export type RsvpStatus = "yes" | "no" | "maybe";
export type UpdateType = "auto" | "manual";

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          username: string | null;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          username?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          username?: string | null;
          created_at?: string;
        };
      };
      entities: {
        Row: {
          id: string;
          type: EntityType;
          name: string;
          slug: string;
          description: string | null;
          address: string | null;
          location: unknown | null; // PostGIS geography point
          banner_url: string | null;
          admin_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          type: EntityType;
          name: string;
          slug: string;
          description?: string | null;
          address?: string | null;
          location?: unknown | null;
          banner_url?: string | null;
          admin_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          type?: EntityType;
          name?: string;
          slug?: string;
          description?: string | null;
          address?: string | null;
          location?: unknown | null;
          banner_url?: string | null;
          admin_id?: string;
          created_at?: string;
        };
      };
      events: {
        Row: {
          id: string;
          title: string;
          slug: string;
          description: string | null;
          address: string | null;
          location: unknown | null; // PostGIS geography point
          starts_at: string;
          ends_at: string | null;
          banner_url: string | null;
          tags: string[] | null;
          created_by: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          description?: string | null;
          address?: string | null;
          location?: unknown | null;
          starts_at: string;
          ends_at?: string | null;
          banner_url?: string | null;
          tags?: string[] | null;
          created_by: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          description?: string | null;
          address?: string | null;
          location?: unknown | null;
          starts_at?: string;
          ends_at?: string | null;
          banner_url?: string | null;
          tags?: string[] | null;
          created_by?: string;
          created_at?: string;
        };
      };
      event_hosts: {
        Row: {
          event_id: string;
          entity_id: string;
          can_edit: boolean;
        };
        Insert: {
          event_id: string;
          entity_id: string;
          can_edit?: boolean;
        };
        Update: {
          event_id?: string;
          entity_id?: string;
          can_edit?: boolean;
        };
      };
      rsvps: {
        Row: {
          id: string;
          user_id: string;
          event_id: string;
          status: RsvpStatus;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          event_id: string;
          status: RsvpStatus;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          event_id?: string;
          status?: RsvpStatus;
          created_at?: string;
        };
      };
      saves: {
        Row: {
          user_id: string;
          event_id: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          event_id: string;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          event_id?: string;
          created_at?: string;
        };
      };
      follows: {
        Row: {
          user_id: string;
          entity_id: string;
          created_at: string;
        };
        Insert: {
          user_id: string;
          entity_id: string;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          entity_id?: string;
          created_at?: string;
        };
      };
      updates: {
        Row: {
          id: string;
          event_id: string;
          type: UpdateType;
          field_changed: string | null;
          old_value: string | null;
          new_value: string | null;
          message: string | null;
          author_id: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          event_id: string;
          type: UpdateType;
          field_changed?: string | null;
          old_value?: string | null;
          new_value?: string | null;
          message?: string | null;
          author_id: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          event_id?: string;
          type?: UpdateType;
          field_changed?: string | null;
          old_value?: string | null;
          new_value?: string | null;
          message?: string | null;
          author_id?: string;
          created_at?: string;
        };
      };
      messages: {
        Row: {
          id: string;
          event_id: string | null;
          entity_id: string;
          from_user_id: string;
          message: string;
          created_at: string;
          read: boolean;
        };
        Insert: {
          id?: string;
          event_id?: string | null;
          entity_id: string;
          from_user_id: string;
          message: string;
          created_at?: string;
          read?: boolean;
        };
        Update: {
          id?: string;
          event_id?: string | null;
          entity_id?: string;
          from_user_id?: string;
          message?: string;
          created_at?: string;
          read?: boolean;
        };
      };
    };
  };
}

// Convenience type aliases for table rows
export type User = Database["public"]["Tables"]["users"]["Row"];
export type Entity = Database["public"]["Tables"]["entities"]["Row"];
export type Event = Database["public"]["Tables"]["events"]["Row"];
export type EventHost = Database["public"]["Tables"]["event_hosts"]["Row"];
export type Rsvp = Database["public"]["Tables"]["rsvps"]["Row"];
export type Save = Database["public"]["Tables"]["saves"]["Row"];
export type Follow = Database["public"]["Tables"]["follows"]["Row"];
export type Update = Database["public"]["Tables"]["updates"]["Row"];
export type Message = Database["public"]["Tables"]["messages"]["Row"];

// Convenience type aliases for inserts
export type UserInsert = Database["public"]["Tables"]["users"]["Insert"];
export type EntityInsert = Database["public"]["Tables"]["entities"]["Insert"];
export type EventInsert = Database["public"]["Tables"]["events"]["Insert"];
export type EventHostInsert = Database["public"]["Tables"]["event_hosts"]["Insert"];
export type RsvpInsert = Database["public"]["Tables"]["rsvps"]["Insert"];
export type SaveInsert = Database["public"]["Tables"]["saves"]["Insert"];
export type FollowInsert = Database["public"]["Tables"]["follows"]["Insert"];
export type UpdateInsert = Database["public"]["Tables"]["updates"]["Insert"];
export type MessageInsert = Database["public"]["Tables"]["messages"]["Insert"];

// Convenience type aliases for updates
export type UserUpdate = Database["public"]["Tables"]["users"]["Update"];
export type EntityUpdate = Database["public"]["Tables"]["entities"]["Update"];
export type EventUpdate = Database["public"]["Tables"]["events"]["Update"];
export type EventHostUpdate = Database["public"]["Tables"]["event_hosts"]["Update"];
export type RsvpUpdate = Database["public"]["Tables"]["rsvps"]["Update"];
export type SaveUpdate = Database["public"]["Tables"]["saves"]["Update"];
export type FollowUpdate = Database["public"]["Tables"]["follows"]["Update"];
export type UpdateUpdate = Database["public"]["Tables"]["updates"]["Update"];
export type MessageUpdate = Database["public"]["Tables"]["messages"]["Update"];
